# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
Solve1 <- function(x) {
    .Call(`_Hmsc_Solve1`, x)
}

#' @export
Solve2 <- function(A, B) {
    .Call(`_Hmsc_Solve2`, A, B)
}

#' @export
Solve2vect <- function(A, B) {
    .Call(`_Hmsc_Solve2vect`, A, B)
}

#' @export
fast_pnorm <- function(x) {
    .Call(`_Hmsc_fast_pnorm`, x)
}

